translation-revision
Edgenesis/shifu.run pull request #165
Opened 2022-10-20 04:11 UTC by rachelzhang0922

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### How is this PR tested:
- [ ] unit test
- [ ] e2e test
- [ ] other (please specify)

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-10-20 06:11 UTC, saiyan86 requested changes

2022-10-20 06:11 UTC, saiyan86 commented on blog-cases/2022-07-14-amazon-casebook.md
> +Edgenesis has provided framework hosting services for many industries, and is now working closely with many domestic and foreign Fortune 500 companies, including CSSC and Xiamen ITG, and has been hon
We should remove Edgenesis related commercial info from shifu.run

2022-10-20 06:11 UTC, saiyan86 commented on blog-cases/2022-06-24-equiptalk.md
>  EquipTalk Ltd. is dedicated to develope software-defined high-end equipments, use aerospace measurement technology to build the next-generation digital base for high-end equipments, build the mapping
EquipTalk Ltd. is dedicated to develop software-defined high-end equipments. Leveraging the aerospace measurement technology as the next-generation digital foundation for high-end equipments, EquipTalk strives to empower high-end equipment in all aspects.

2022-10-20 06:11 UTC, saiyan86 commented on blog-cases/2022-07-14-amazon-casebook.md
> -## Building a Full-stack IoT Solution Architecture
Building is correct

2022-10-23 06:25 UTC, tomqin93 approved these changes

2022-10-25 01:31 UTC, merged