Chinese version of three docs
Edgenesis/shifu.run pull request #174
Opened 2022-10-25 13:34 UTC by rachelzhang0922

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### How is this PR tested:
- [ ] unit test
- [ ] e2e test
- [ ] other (please specify)

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-10-25 13:45 UTC, tomqin93 requested changes
@rachelzhang0922 added some comment, please take a look

2022-10-25 13:45 UTC, tomqin93 commented on i18n/zh-Hans/docusaurus-plugin-content-docs/current/guides/stub/http-to-powershell.md
> +title: HTTP 到 PowerShell 的 Stub
Stub => 中间件, same for other occurrences

2022-10-25 13:45 UTC, tomqin93 commented on i18n/zh-Hans/docusaurus-plugin-content-docs/current/guides/stub/http-to-powershell.md
> +#### 将HTTP主体代理到PowerShell shell并执行
主体 => 请求体

2022-10-26 01:35 UTC, tomqin93 commented
@rachelzhang0922 pipeline has failed for this PR, please take a look 
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/4149598/197913877-7545fc00-2570-41c2-bc5a-8bc411fe1d8f.png">

2022-10-26 06:07 UTC, tomqin93 requested changes
@rachelzhang0922 added 1 comment, please take a look

2022-10-26 06:07 UTC, tomqin93 commented on i18n/zh-Hans/docusaurus-plugin-content-docs/current/guides/stub/http-to-ssh.md
> +title: HTTP 到 SSH 的 Stub
let's keep everything consistent, same for other occurrences 
Stub => 中间件

2022-10-27 01:52 UTC, Yang-Xijie commented
It will be great to add spaces around English word in Chinese. @rachelzhang0922 

<img width="833" alt="image" src="https://user-images.githubusercontent.com/57952362/198172435-555b52e9-64a6-4fff-b8da-af690ff13521.png">

I will fix it in this PR soon.

2022-10-27 01:54 UTC, Yang-Xijie commented
Please do pay attention to markdown grammar... @rachelzhang0922 Double-check it before you make commits.

<img width="299" alt="image" src="https://user-images.githubusercontent.com/57952362/198172575-126553a6-1cad-49b1-b396-f9cbd26810c2.png">

2022-10-27 08:29 UTC, tomqin93 approved these changes
LGTM

2022-10-27 08:34 UTC, merged