add explanation
Edgenesis/shifu.run pull request #176
Opened 2022-10-27 08:30 UTC by rachelzhang0922

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### How is this PR tested:
- [ ] unit test
- [ ] e2e test
- [ ] other (please specify)

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-10-27 10:02 UTC, tomqin93 requested changes
@rachelzhang0922 added some comments, please take a look

2022-10-27 10:02 UTC, tomqin93 commented on docs/references/words.md
> +- A powerful cloud native eco-system. You can find almost every tool you need in the CNCF cloud native landscape. And being k8s native, Shifu is compatible with every single one of them.
should we capitalize `K` in all K8s?

2022-10-27 10:11 UTC, BtXin commented on i18n/zh-Hans/docusaurus-plugin-content-docs/current/references/words.md
> +  - Shifu是一个[Kubernetes CRD](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/)
shifu不是CRD

2022-10-27 10:12 UTC, rachelzhang0922 commented on i18n/zh-Hans/docusaurus-plugin-content-docs/current/references/words.md
> +  - Shifu是一个[Kubernetes CRD](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/)
怎么说更好一点？

2022-10-28 02:25 UTC, BtXin commented on i18n/zh-Hans/docusaurus-plugin-content-docs/current/references/words.md
> +  - Shifu是一个[Kubernetes CRD](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/)
EdgeDevice不才是CRD嘛。。。

2022-10-28 07:51 UTC, rachelzhang0922 commented on docs/references/words.md
> +  - By using Shifu, developers can connect, monitor and control any IoT device more easily
i'd stick to the original statement, it emphasizes the latter part

2022-10-28 07:55 UTC, rachelzhang0922 commented on docs/references/words.md
> +- Vendor lock-in. We all know it's pretty hard to migrate from one public cloud to another. For example, Google Cloud will shutter its IoT Core service in 2023.
shutter is correct

2022-10-28 07:56 UTC, rachelzhang0922 commented on docs/references/words.md
> +- High cost. Given the big data & massive scale nature of IoT, running complete solutions on public clouds can be very costly.
I think we should stress the high cost here

2022-10-28 07:58 UTC, rachelzhang0922 commented on i18n/zh-Hans/docusaurus-plugin-content-docs/current/references/words.md
> +  - Shifu是一个[Kubernetes CRD](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/)
I need a correct statement I could use

2022-10-28 09:56 UTC, tomqin93 approved these changes
LGTM

2022-10-28 10:04 UTC, BtXin commented on i18n/zh-Hans/docusaurus-plugin-content-docs/current/references/words.md
> +  - Shifu是一个[Kubernetes CRD](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/)
这CRD定义里：https://github.com/Edgenesis/shifu/blob/main/pkg/k8s/crd/install/shifu_install.yml#L18 
https://github.com/Edgenesis/shifu/blob/main/pkg/k8s/crd/install/shifu_install.yml#L145
俩CRD一个叫edgeDevice，一个叫telemetryService，然而并没有一个叫shifu的crd。。。这里写shifu是CRD太confusing了吧 @saiyan86

2022-11-01 09:27 UTC, merged