add-tdengine-telemetry
Edgenesis/shifu.run pull request #192
Opened 2022-11-16 05:57 UTC by rachelzhang0922

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### How is this PR tested:
- [ ] unit test
- [ ] e2e test
- [ ] other (please specify)

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-11-16 06:06 UTC, tomqin93 requested changes
@rachelzhang0922 added some comment, please make changes accordingly

2022-11-16 06:06 UTC, tomqin93 commented on docs/guides/telemetryservice/pushtoTDEngine.md
> +      dbtype: TDEngine
TDengine with lowercase e, same for the Chinese version

2022-11-16 06:06 UTC, tomqin93 commented on docs/guides/telemetryservice/pushtoTDEngine.md
> +***Shifu*** can push your data from telemetry to your MQTT Broker
from device to your TDengine database

2022-11-16 06:06 UTC, tomqin93 commented on docs/guides/telemetryservice/pushtoTDEngine.md
> +           telemetryCollectionService: push-endpoint-1 # Edit it to the name same with TelemetryService's name(# tag)
add an extra space for this line, same for the Chinese version

2022-11-16 06:06 UTC, tomqin93 commented on docs/guides/telemetryservice/pushtoTDEngine.md
> +:::note
add a newline before this line, same for the Chinese version

2022-11-16 06:06 UTC, tomqin93 commented on docs/guides/telemetryservice/pushtoTDEngine.md
> +Then you need to deploy deviceShifu again so that the telemetry will push raw data to the telemetry service and publish it to your MQTT broker.
MQTT broker => TDengine database, same for the Chinese version

2022-11-16 06:06 UTC, tomqin93 commented on i18n/zh-Hans/docusaurus-plugin-content-docs/current/guides/telemetryservice/pushtoTDEngine.md
> +如果你有多个遥测服务，你可以把它们写在一个文件里，用`------`把它们分割该文件文件。
`------` => `---`

2022-11-16 06:38 UTC, tomqin93 requested changes
@rachelzhang0922 added some comment, please take a look

2022-11-16 06:38 UTC, tomqin93 commented on docs/guides/telemetryservice/pushtoTDEngine.md
> +***Shifu*** can push your data device to your TDengine database
***Shifu*** can push data from your device to a TDengine database

2022-11-16 06:38 UTC, tomqin93 commented on docs/guides/telemetryservice/pushtoTDEngine.md
> +- `secret` is your code
`secret` is your database password

2022-11-16 06:38 UTC, tomqin93 commented on docs/guides/telemetryservice/pushtoTDEngine.md
> +- `username` is your username
`username` is your database username

2022-11-16 06:38 UTC, tomqin93 commented on docs/guides/telemetryservice/pushtoTDEngine.md
> +           telemetryCollectionService: push-endpoint-1 # Edit it to the name same with TelemetryService's name(# tag)
```yaml
data:
  telemetries: |
    telemetries:
      device_health1:
        properties:
          instruction: status
          pushSettings:
            telemetryCollectionService: push-endpoint-1 # Edit it to the name same with TelemetryService's name(# tag)
```

2022-11-16 06:53 UTC, tomqin93 approved these changes
LGTM

2022-11-16 06:53 UTC, tomqin93 commented
@MrLeea-13155bc  please review

2022-11-16 14:46 UTC, MrLeea-13155bc reviewed
@rachelzhang0922 add some comments

2022-11-16 14:46 UTC, MrLeea-13155bc commented on docs/guides/telemetryservice/pushtoTDEngine.md
> +- `dbTable` is the table of the database
table name?

2022-11-16 14:46 UTC, MrLeea-13155bc commented on docs/guides/telemetryservice/pushtoTDEngine.md
> +[https://github.com/Edgenesis/shifu/tree/main/examples/httpDeviceShifu/deployment](https://github.com/Edgenesis/shifu/tree/main/examples/httpDeviceShifu/deployment)
I think it should use following example is better `https://github.com/Edgenesis/shifu/tree/main/examples/tdengineTelemetryService/deployment`

2022-11-16 14:46 UTC, MrLeea-13155bc commented on docs/guides/telemetryservice/pushtoTDEngine.md
> +            telemetryCollectionService: push-endpoint-1 # Edit it to the name same with TelemetryService's name(# tag)
It seems that the tag comment is removed, how about remove `(# tag)`

2022-11-16 14:46 UTC, MrLeea-13155bc commented on i18n/zh-Hans/docusaurus-plugin-content-docs/current/guides/telemetryservice/pushtoTDEngine.md
> +然后你需要再次部署 deviceshifu ，这样遥测就会将采集到的数据推送到遥测服务，并将其发布到你的 TDEngine数据库 中。
remove unnecessary space

2022-11-16 14:46 UTC, MrLeea-13155bc commented on i18n/zh-Hans/docusaurus-plugin-content-docs/current/guides/telemetryservice/pushtoTDEngine.md
> +## 再次部署deviceshifu
deviceShifu

2022-11-16 14:46 UTC, MrLeea-13155bc commented on i18n/zh-Hans/docusaurus-plugin-content-docs/current/guides/telemetryservice/pushtoTDEngine.md
> +[https://github.com/Edgenesis/shifu/tree/main/examples/httpDeviceShifu/deployment](https://github.com/Edgenesis/shifu/tree/main/examples/httpDeviceShifu/deployment)
ditto

2022-11-16 14:46 UTC, MrLeea-13155bc commented on i18n/zh-Hans/docusaurus-plugin-content-docs/current/guides/telemetryservice/pushtoTDEngine.md
> +            telemetryCollectionService: push-endpoint-1 # Edit it to the name same with TelemetryService's name(# tag)
ditto

2022-11-23 05:31 UTC, MrLeea-13155bc reviewed
@rachelzhang0922 add a comment rest look good

2022-11-23 05:31 UTC, MrLeea-13155bc commented on i18n/zh-Hans/docusaurus-plugin-content-docs/current/guides/telemetryservice/pushtoTDEngine.md
> +然后你需要再次部署 deviceshifu ，这样遥测就会将采集到的数据推送到遥测服务，并将其发布到你的 TDEngine数据库中。
`deviceshifu` => `deviceShifu` `TDEngine` => `TDengine`

2022-11-23 05:34 UTC, MrLeea-13155bc approved these changes

2022-11-23 05:56 UTC, merged