mqtt multi-topic update
Edgenesis/shifu.run pull request #207
Opened 2022-12-14 10:06 UTC by cbgz121

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### How is this PR tested:
- [ ] unit test
- [ ] e2e test
- [ ] other (please specify)

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-12-14 10:40 UTC, tomqin93 requested changes
@cbgz121 need to update the API reference section too https://github.com/Edgenesis/shifu.run/blob/main/docs/references/api/deviceshifu-configmap.md#deviceshifuinstruction

2022-12-14 10:48 UTC, cbgz121 commented
> @cbgz121 need to update the API reference section too https://github.com/Edgenesis/shifu.run/blob/main/docs/references/api/deviceshifu-configmap.md#deviceshifuinstruction

but the api reference part is a general document, which does not specify a specific protocol, so there is no need to update it?

2022-12-14 10:51 UTC, tomqin93 commented
> > @cbgz121 need to update the API reference section too https://github.com/Edgenesis/shifu.run/blob/main/docs/references/api/deviceshifu-configmap.md#deviceshifuinstruction
> 
> but the api reference part is a general document, which does not specify a specific protocol, so there is no need to update it?

Yes, we need to fill in protocol specific settings as we implement them

2022-12-16 11:16 UTC, tomqin93 requested changes
@cbgz121 added some comment, overall looks good

2022-12-16 11:16 UTC, tomqin93 commented on docs/references/api/deviceshifu-configmap.md
> +DeviceShifuprotocolPropertyList   parameters of the ***deviceShifu*** command, which have various configurations according to different protocols.The following shows the use of MQTT protocol and OPC
remove extra spaces after "DeviceShifuprotocolPropertyList"
add a space after "different protocols."
remove extra spaces between "the  examples"

2022-12-16 11:16 UTC, tomqin93 commented on docs/guides/cases/connect-mqtt.md
> +{"mqtt_message":"test_topicmsg1","mqtt_receive_timestamp":"2022-04-29 08:57:49.9492744 +0000 UTC m=+75.407609501"}
let's use a different `mqtt_message` value to avoid confusion between the topic and message

2022-12-16 11:16 UTC, tomqin93 commented on docs/references/api/deviceshifu-configmap.md
> +      ... # The command and the name and number of nodeids you want to associate can be configured by yourself, just continue to add according to this format
number of nodeids => value of NodeID

2022-12-16 11:16 UTC, tomqin93 commented on docs/tutorials/demo-try.md
> +  A: We support multi-channel subscription, so multiple commands can be sent to MQTT's digital twin (eg: get_topicmsg1, get_topicmsg2), When MQTT's digital twin receives the mqtt_data command, it ret
multi-channel => multi-topic
so multiple commands can be sent to MQTT's digital twin => so we can have multiple APIs for MQTT's digital twin

2022-12-16 11:16 UTC, tomqin93 commented on docs/tutorials/demo-try.md
> +We can use mosquitto to publish data to multiple channels to MQTT server. (The data after -m is the information we posted)
channels => topics

2022-12-16 11:16 UTC, tomqin93 commented on i18n/zh-Hans/docusaurus-plugin-content-docs/current/guides/cases/connect-mqtt.md
> +      get_topicmsg2: # 订阅多个topic时修改此值
The comment seems confusing, each instruction corresponds to one topic, we cannot subscribe multiple topics with one instruction

2022-12-16 11:16 UTC, tomqin93 commented on i18n/zh-Hans/docusaurus-plugin-content-docs/current/guides/cases/connect-mqtt.md
> +{"mqtt_message":"test_topicmsg1","mqtt_receive_timestamp":"2022-04-29 08:57:49.9492744 +0000 UTC m=+75.407609501"}
same as above

2022-12-16 11:16 UTC, tomqin93 commented on i18n/zh-Hans/docusaurus-plugin-content-docs/current/tutorials/demo-try.md
> +  A：我们支持多频道订阅，所以可以向MQTT的数字孪生发送多个命令(例：get_topicmsg1、get_topicmsg2)，当 MQTT 的数字孪生接收到命令时，会返回订阅频道中最后一条消息。
多频道 => 多主题
所以MQTT的数字孪生可以拥有多个API

2022-12-16 11:16 UTC, tomqin93 commented on docs/guides/cases/connect-mqtt.md
> +          MQTTTopic: "/test/test2" # change this value when subscribing to multiple topics
ditto

2022-12-19 02:13 UTC, tomqin93 approved these changes
LGTM

2022-12-19 02:59 UTC, merged